services:
  - type: web
    name: comparador-supermercados
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: gunicorn app:app
